
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T21:55:37+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9353c4a52d53336fc44bd6c51e8b51cab9da684",
 "version": "0.post1+gd9353c4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
