
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T22:03:29+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "301c38b2e6ad21671aba12d7a84c816046608ca3",
 "version": "0.post1+g301c38b"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
