
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-04-17T22:04:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b0c0325b568fd17127e4ace20573267a477d794f",
 "version": "0.post1+gb0c0325"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
