name: CI


on:
  push:
    branches: main
  pull_request:
    branches: main


jobs:
    build:
      runs-on: ${{ matrix.os }}
        
      strategy:
        matrix:
          os: [ubuntu-22.04]

      steps:
        - name: CHeckout Repo
          uses: actions/checkout@v3
        - name: Install
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: which python
        - name: Run installation.
          run: |
            pip install .
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            python setup.py install
        # - name: Test coverage.
        #   run: |
        #     python setup.py test
        # - name: Flake8
        #   run: |
        #     flake8  --max-line-length=115
        - name: Make docs
          run: |
            make -C docs build
        - name: Deploy Website
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
